name: Release

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 20

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

  publish:
    runs-on: windows-latest
    needs: build
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'  # Condition to trigger only on main branch pushes
    steps:
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        with:
          tag_name: v1.0.0  # Adjust to a specific version/tag if needed
          release_name: Release v1.0.0
          draft: false
          prerelease: false

      - name: Upload latest.yml
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: path/to/latest.yml  # Adjust to the path of your latest.yml file
          asset_name: latest.yml
          asset_content_type: application/yaml  # Adjust content type as needed
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}